backend:
  name: git-gateway
  repo: hila-amit-website/johnnybar.github.io
  branch: master
  site_domain: https://laughing-pare-df22f2.netlify.com/

media_folder: "img"
publish_mode: editorial_workflow
public_folder: "/"


collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Homepage"
        name: "Homepage"
        file: "/"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}